# Dependencies

pygments:            true

# Permalinks
permalink:           pretty
relative_permalinks: true

# Setup
title:               Tjelvar Olsson
tagline:             'using computers to do better science'
url:                 http://tjelvarolsson.com
paginate:            1
baseurl:             /

author:
  name:              Tjelvar Olsson
  url:               https://twitter.com/tjelvar_olsson

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/tjelvar-olsson/tjelvar-olsson.github.io

# List of pages to include in the header of the website
pages_list:
  About:            '/about/'
  Feed:             '/atom.xml'
